# Vendistri currently relies on AndroidX, Compose, OkHttp, and Mapbox consumer
# rules supplied by those libraries. Keep application-specific rules here as
# reflection-based features are introduced.

# Mapbox Directions models are generated by AutoValue. These annotations are
# compile-time-only and are not required by the generated runtime classes.
-dontwarn com.google.auto.value.AutoValue
-dontwarn com.google.auto.value.AutoValue$Builder

# WorkManager creates its Room database implementation by generated class name.
# R8 cannot see that reflective construction and otherwise removes WorkDatabase_Impl,
# causing release builds to crash in InitializationProvider before MainActivity starts.
-keep class androidx.work.impl.WorkDatabase_Impl { *; }
-keep class androidx.work.impl.model.*_Impl { *; }
